# Site settings
title: "Catan Enterprises, LLC"
location: "Helena, MT"
email: info@catanenterprises.com
description: "Performing high-efficiency infill development to promote a walkable, more vibrant city environment for our tenants and ourselves"

url: "https://jenningsanderson.com/Catan-Enterprises" # the base hostname & protocol for your site


# Build settings
markdown: kramdown


#Add the properties collection
collections:
  properties:
    output: true


#Custom variables
images: "https://jenningsanderson.com/Catan-Enterprises/assets/images"
