# Site settings
title: "Catan Enterprises, LLC"
location: "Helena, MT"
email: catanenterprises@gmail.com
description: "Performing high-efficiency infill development, to promote a walkable, more vibrant city environment for our tenants and ourselves"

url: "http://www.catanenterprises.com" # the base hostname & protocol for your site


# Build settings
markdown: kramdown


#Add the properties collection
collections:
  properties:
    output: true